name: Python Docs (Sphinx)

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install doc dependencies
        run: |
          python -m pip install --upgrade pip wheel
          # Paquetes de Sphinx (agregá los que uses en tus .rst/.md)
          pip install "sphinx>=7" "sphinx-rtd-theme>=2" myst-parser sphinx-tabs
          # Instalar tu paquete para que autodoc pueda importarlo
          pip install -e ./client/python/projectairsim

      - name: Build API stubs (sphinx-apidoc)
        working-directory: ./client/python/projectairsim/docs
        run: |
          rm -rf _api
          sphinx-apidoc -o ./_api ../src/projectairsim -f -e

      - name: Build Sphinx HTML
        working-directory: ./client/python/projectairsim/docs
        run: |
          rm -rf build/html
          sphinx-build -b html -W --keep-going -n -T . build/html

      - name: Copy API docs into repo docs folder
        run: |
          rm -rf docs/api_docs
          mkdir -p docs/api_docs
          cp -r ./client/python/projectairsim/docs/build/html/* docs/api_docs/

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/api_docs
