name: Build and Deploy Sphinx Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Si tu runner es Linux, esto va bien. (En macOS usar sed -i '' ...)
      - name: Strip "docs/" prefixes from README
        run: sed -i 's|docs/||g' README.md

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Upgrade pip & build tooling
        run: python -m pip install --upgrade pip build setuptools wheel

      # ✅ Instalar TU paquete (editable) desde donde está el pyproject.toml
      - name: Install projectairsim (editable)
        run: python -m pip install -e ./client/python/projectairsim

      # (Opcional) Si querés mockear deps pesadas en Sphinx, destildá y ajustá conf.py:
      # - name: Print tip for mocking heavy deps
      #   run: |
      #     echo "Podés agregar en conf.py: autodoc_mock_imports = ['open3d','torch','onnxruntime','cv2']"

      - name: Verify installation
        run: |
          python -m pip show projectairsim || true
          python - << 'PY'
          import projectairsim, sys
          print("projectairsim loaded from:", projectairsim.__file__)
          PY

      - name: Install dependencies for main docs
        working-directory: ./docs
        run: python -m pip install -r requirements.txt

      - name: Build Python client docs
        working-directory: ./client/python/projectairsim/docs
        run: |
          rm -rf build
          make html

      - name: Build main docs
        working-directory: ./docs
        run: |
          rm -rf build
          make html

      - name: Copy Python client docs into main docs
        run: |
          mkdir -p docs/build/html/client_api
          cp -r client/python/projectairsim/docs/build/html/* docs/build/html/client_api/

      - name: Deploy to gh_page branch
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh_page
          force_orphan: true
